// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAeB967A8PjB6OtQwxKB8fZDFBET-hjr4g',
    appId: '1:514958179535:web:39f6fc97e9fefb337acbba',
    messagingSenderId: '514958179535',
    projectId: 'expensetracker-bb194',
    authDomain: 'expensetracker-bb194.firebaseapp.com',
    storageBucket: 'expensetracker-bb194.firebasestorage.app',
    measurementId: 'G-QQWN2KW85C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBARmC0u0pC30vCaKvnFBm8jOeLs9pTdts',
    appId: '1:514958179535:android:cf201f89a7b835357acbba',
    messagingSenderId: '514958179535',
    projectId: 'expensetracker-bb194',
    storageBucket: 'expensetracker-bb194.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAaz05jfN2hYeu1y9FJP1nAF26FmJWjd9Y',
    appId: '1:514958179535:ios:390ae213ffb861207acbba',
    messagingSenderId: '514958179535',
    projectId: 'expensetracker-bb194',
    storageBucket: 'expensetracker-bb194.firebasestorage.app',
    iosClientId: '514958179535-lhlo8157gf88ggk0hkadi4vujq7fkvpk.apps.googleusercontent.com',
    iosBundleId: 'com.example.expenseTracker',
  );
}
